import { renderNativeObject, type NativeRenderState } from './nativeAssets';
import ElevationLegend from './ElevationLegend';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Crosshair, Grid2X2, Minus, Plus, Trees, Maximize2, Mountain } from 'lucide-react';
import { ASSETS } from './domain';
import { nextZoom, cancelsActiveStroke } from './viewportMath';
import { Button } from './ui';
import { PLAYER_COLORS, renderObject } from './mapObjects';
import { renderScene, terrainColor, objectBounds, objectDepth } from './terrainRendering';
import { TILE_WIDTH as TW, TILE_HEIGHT as TH, ELEVATION_HEIGHT as EH, brushCells, createHeightField, editElevation, interpolateStroke, objectGround, pickTerrain, projectVertex, tileVertices, type ElevationMode, type Point } from './terrainGeometry';
import type { Project, MapObject, Tool } from './types';

interface Props {nativeAssets?:NativeRenderState;project:Project;tool:Tool;terrain:number;asset:number;player:number;brush:number;elevationMode:ElevationMode;elevationTarget:number;selected:string|null;onSelect:(id:string|null)=>void;onCommit:(p:Project,label:string)=>void;onHover:(tile:{x:number,y:number,elevation?:number}|null)=>void;fitSignal:number;grid:boolean;onGrid:()=>void}
export default function MapViewport({nativeAssets,project,tool,terrain,asset,player,brush,elevationMode,elevationTarget,selected,onSelect,onCommit,onHover,fitSignal,grid,onGrid}:Props) {
 const canvasRef=useRef<HTMLCanvasElement>(null),miniRef=useRef<HTMLCanvasElement>(null),containerRef=useRef<HTMLDivElement>(null),sceneRef=useRef<HTMLCanvasElement|null>(null);
 const [size,setSize]=useState({w:800,h:550}),[camera,setCamera]=useState({x:400,y:80,zoom:1}),[hover,setHover]=useState<Point|null>(null),[draft,setDraft]=useState<Project|null>(null),[showObjects,setShowObjects]=useState(true),[contours,setContours]=useState(true),[space,setSpace]=useState(false),[sceneVersion,setSceneVersion]=useState(0),[measured,setMeasured]=useState(false),[sceneRequest,setSceneRequest]=useState(0);
 const renderedCamera=useRef(camera);
 const active=draft||project,field=useMemo(()=>createHeightField(active.map),[active.map]);
 const draftRef=useRef<Project|null>(null),projectRef=useRef(project);projectRef.current=project;
 const interaction=useRef<{mode:'pan'|'paint'|'move';x:number;y:number;cx:number;cy:number;id?:string;last?:Point;touched:Set<number>}|null>(null);
 useEffect(()=>{interaction.current=null;draftRef.current=null;setDraft(null);},[project]);
 const initialView=useRef<{signal:number;width:number;height:number;projectId:string}|null>(null);
 const frameScene=useCallback(()=>{const p=projectRef.current,main=p.objects.find(o=>o.nativeId===109)||p.objects.find(o=>o.category==='building'),actor=p.objects.find(o=>/林川|引路/.test(o.label)),x=main?(main.x+(actor?.x??main.x))/2:p.map.width/2,y=main?(main.y+(actor?.y??main.y))/2:p.map.height/2,field=createHeightField(p.map),point=projectVertex(objectGround(field,{x,y} as MapObject)),z=Math.max(.42,Math.min(.85,size.w/900));setCamera({x:size.w/2-point.x*z,y:size.h/2-point.y*z+15,zoom:z});},[size]);
 const fit=useCallback(()=>{const map=projectRef.current.map,maxHeight=map.tiles.reduce((m,t)=>Math.max(m,t.elevation),0),mapHeight=(map.width+map.height)*TH/2+maxHeight*EH;const z=Math.max(.01,Math.min(1.6,(size.w-80)/((map.width+map.height)*TW/2),(size.h-90)/mapHeight));setCamera({x:size.w/2+(map.height-map.width)*TW/4*z,y:(size.h-mapHeight*z)/2+maxHeight*EH*z,zoom:z});},[size,project.map.width,project.map.height]);
 useEffect(()=>{const el=containerRef.current;if(!el)return;const observer=new ResizeObserver(entries=>{const r=entries[0].contentRect;setSize({w:r.width,h:r.height});setMeasured(true);});observer.observe(el);return()=>observer.disconnect();},[]);
 useEffect(()=>{if(!measured)return;const previous=initialView.current;if(!previous||previous.projectId!==project.id)frameScene();else if(previous.signal!==fitSignal||previous.width!==project.map.width||previous.height!==project.map.height)fit();initialView.current={signal:fitSignal,width:project.map.width,height:project.map.height,projectId:project.id};},[fit,frameScene,fitSignal,measured,project.map.width,project.map.height,project.id]);
 useEffect(()=>{const cancel=()=>{interaction.current=null;draftRef.current=null;setDraft(null);setSpace(false);setSceneRequest(v=>v+1);};const down=(e:KeyboardEvent)=>{if(cancelsActiveStroke(e)&&interaction.current){e.preventDefault();e.stopImmediatePropagation();cancel();return;}if(e.code==='Space'&&e.target===canvasRef.current){e.preventDefault();setSpace(true);}},up=(e:KeyboardEvent)=>{if(e.code==='Space')setSpace(false);};window.addEventListener('keydown',down,true);window.addEventListener('keyup',up);window.addEventListener('blur',cancel);return()=>{window.removeEventListener('keydown',down,true);window.removeEventListener('keyup',up);window.removeEventListener('blur',cancel);};},[]);
 const screenToMap=(sx:number,sy:number)=>pickTerrain(field,{x:(sx-camera.x)/camera.zoom,y:(sy-camera.y)/camera.zoom});
 const zoom=useCallback((factor:number,sx=size.w/2,sy=size.h/2)=>setCamera(c=>{const z=nextZoom(c.zoom,factor),r=z/c.zoom;return{x:sx-(sx-c.x)*r,y:sy-(sy-c.y)*r,zoom:z};}),[size]);
 useEffect(()=>{const c=canvasRef.current;if(!c)return;const handler=(e:WheelEvent)=>{e.preventDefault();const r=c.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top);};c.addEventListener('wheel',handler,{passive:false});return()=>c.removeEventListener('wheel',handler);},[zoom]);
 // Cache the expensive scene. Hover feedback and brush outlines redraw independently.
 useEffect(()=>{if(interaction.current?.mode==='pan')return;const timer=setTimeout(()=>{const scene=sceneRef.current||(sceneRef.current=document.createElement('canvas')),dpr=Math.min(window.devicePixelRatio||1,2);scene.width=size.w*dpr;scene.height=size.h*dpr;const ctx=scene.getContext('2d')!;ctx.scale(dpr,dpr);renderScene(ctx,field,active.objects,{width:size.w,height:size.h,camera,grid,contours,showObjects,selected,nativeAssets});renderedCamera.current=camera;setSceneVersion(v=>v+1);},interaction.current?.mode==='paint'?80:sceneRef.current&&camera!==renderedCamera.current?70:0);return()=>clearTimeout(timer);},[field,active.objects,size,camera,grid,contours,showObjects,selected,sceneRequest,nativeAssets]);
 useEffect(()=>{const c=canvasRef.current,scene=sceneRef.current;if(!c||!scene)return;const dpr=Math.min(window.devicePixelRatio||1,2);c.width=size.w*dpr;c.height=size.h*dpr;const ctx=c.getContext('2d')!;ctx.fillStyle='#202932';ctx.fillRect(0,0,c.width,c.height);const previous=renderedCamera.current,ratio=camera.zoom/previous.zoom;ctx.save();ctx.translate((camera.x-previous.x*ratio)*dpr,(camera.y-previous.y*ratio)*dpr);ctx.scale(ratio,ratio);ctx.drawImage(scene,0,0);ctx.restore();ctx.scale(dpr,dpr);ctx.save();ctx.translate(camera.x,camera.y);ctx.scale(camera.zoom,camera.zoom);
  if(hover){for(const p of brushCells(active.map,hover,['terrain','elevation','erase'].includes(tool)?brush:1)){const points=tileVertices(field,p.x,p.y).slice(0,4).map(projectVertex);ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=tool==='erase'?'#ed736340':tool==='elevation'?'#e8d2a540':'#beddf82c';ctx.fill();ctx.strokeStyle=tool==='elevation'?'#efc575':'#d3e8ffb0';ctx.lineWidth=1.2/camera.zoom;ctx.stroke();}
   if(tool==='object'){ctx.globalAlpha=.6;const a=ASSETS.find(a=>a.id===asset),o:MapObject={id:'preview',nativeId:asset,player,x:hover.x+.5,y:hover.y+.5,rotation:0,label:'',category:a?.category||'unit'},p=projectVertex(objectGround(field,o));renderObject(ctx,o,p.x,p.y,false);ctx.globalAlpha=1;}
  }
  ctx.restore();const picked=active.objects.find(o=>o.id===selected);if(picked&&showObjects){const p=projectVertex(objectGround(field,picked)),sx=p.x*camera.zoom+camera.x,sy=p.y*camera.zoom+camera.y-(picked.category==='building'?80:50)*camera.zoom-14;ctx.font='600 12px system-ui';ctx.textAlign='center';const label=picked.label||`ID ${picked.nativeId}`,w=ctx.measureText(label).width+16;ctx.fillStyle='#192537ed';ctx.fillRect(sx-w/2,sy-13,w,23);ctx.strokeStyle='#8ab4ff';ctx.lineWidth=1;ctx.strokeRect(sx-w/2,sy-13,w,23);ctx.fillStyle='#edf0f5';ctx.fillText(label,sx,sy+3);}
 },[sceneVersion,active,field,size,camera,hover,tool,brush,selected,showObjects,asset,player]);
 useEffect(()=>{const c=miniRef.current;if(!c)return;const ctx=c.getContext('2d')!,{width:w,height:h,tiles}=active.map;c.width=w;c.height=h;const image=ctx.createImageData(w,h);tiles.forEach((t,i)=>{const n=parseInt(terrainColor(t.terrain).slice(1),16),x=i%w,y=Math.floor(i/w),left=tiles[y*w+Math.max(0,x-1)].elevation,shade=(t.elevation-left)*16+t.elevation*2;image.data[i*4]=(n>>16)+shade;image.data[i*4+1]=((n>>8)&255)+shade;image.data[i*4+2]=(n&255)+shade;image.data[i*4+3]=255;});ctx.putImageData(image,0,0);active.objects.filter(o=>o.category!=='decoration').forEach(o=>{ctx.fillStyle=PLAYER_COLORS[o.player];ctx.fillRect(o.x-1,o.y-1,2,2);});},[active]);
 const position=(e:React.PointerEvent)=>{const r=e.currentTarget.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};};
 const hitObject=(s:Point)=>{if(!showObjects)return;const point={x:(s.x-camera.x)/camera.zoom,y:(s.y-camera.y)/camera.zoom},ground=pickTerrain(field,point),pixel=document.createElement('canvas');pixel.width=pixel.height=1;const ctx=pixel.getContext('2d',{willReadFrequently:true})!;return [...active.objects].sort((a,b)=>objectDepth(b)-objectDepth(a)).find(o=>{const b=objectBounds(o,field,nativeAssets);if(point.x<b.x||point.x>b.x+b.width||point.y<b.y||point.y>b.y+b.height||ground&&ground.depth>objectDepth(o)+.02)return false;ctx.clearRect(0,0,1,1);ctx.save();ctx.translate(-point.x,-point.y);if(!renderNativeObject(ctx,o,b.point.x,b.point.y,nativeAssets))renderObject(ctx,o,b.point.x,b.point.y,false);ctx.restore();return ctx.getImageData(0,0,1,1).data[3]>32;});};
 const paint=(p:Point)=>{const i=interaction.current;if(!i)return;let next=draftRef.current||project;const points=interpolateStroke(i.last||p,p);for(const point of points){if(tool==='elevation'){const map=editElevation(next.map,point,brush,elevationMode,elevationTarget,i.touched);if(map!==next.map)next={...next,map};}else if(tool==='terrain'){const cells=brushCells(next.map,point,brush),changes=new Set(cells.map(p=>p.y*next.map.width+p.x).filter(index=>next.map.tiles[index].terrain!==terrain));if(changes.size)next={...next,map:{...next.map,tiles:next.map.tiles.map((t,index)=>changes.has(index)?{...t,terrain}:t)}};}else if(tool==='erase'){const objects=next.objects.filter(o=>o.locked||Math.hypot(o.x-point.x-.5,o.y-point.y-.5)>brush);if(objects.length!==next.objects.length)next={...next,objects};}}i.last=p;if(next!==project){draftRef.current=next;setDraft(next);}};
 const pointerDown=(e:React.PointerEvent<HTMLCanvasElement>)=>{e.currentTarget.focus();e.currentTarget.setPointerCapture(e.pointerId);const s=position(e),p=screenToMap(s.x,s.y),base={x:s.x,y:s.y,cx:0,cy:0,touched:new Set<number>()};if(e.button===1||e.button===2||space||tool==='pan'){interaction.current={...base,mode:'pan',cx:camera.x,cy:camera.y};return;}if(tool==='select'){const hit=hitObject(s);onSelect(hit?.id||null);if(hit&&!hit.locked)interaction.current={...base,mode:'move',id:hit.id};return;}if(!p)return;if(['terrain','elevation','erase'].includes(tool)){interaction.current={...base,mode:'paint'};paint(p);}else if(tool==='object'){const a=ASSETS.find(a=>a.id===asset);const o:MapObject={id:crypto.randomUUID(),nativeId:asset,player,x:p.x+.5,y:p.y+.5,rotation:0,label:a?.name||`ID ${asset}`,category:a?.category||'unit'};onCommit({...project,objects:[...project.objects,o]},`放置 ${o.label}`);onSelect(o.id);}};
 const pointerMove=(e:React.PointerEvent<HTMLCanvasElement>)=>{const s=position(e),p=screenToMap(s.x,s.y);setHover(p);onHover(p?{x:p.x,y:p.y,elevation:active.map.tiles[p.y*active.map.width+p.x].elevation}:null);const i=interaction.current;if(!i)return;if(i.mode==='pan')setCamera(c=>({...c,x:i.cx+s.x-i.x,y:i.cy+s.y-i.y}));else if(i.mode==='paint'&&p)paint(p);else if(i.mode==='move'&&p&&Math.hypot(s.x-i.x,s.y-i.y)>3){const next={...project,objects:project.objects.map(o=>o.id===i.id?{...o,x:p.x+.5,y:p.y+.5}:o)};draftRef.current=next;setDraft(next);}};
 const finish=()=>{if(draftRef.current){onCommit(draftRef.current,interaction.current?.mode==='move'?'移动对象':tool==='terrain'?'绘制地形':tool==='elevation'?{raise:'抬高地形',lower:'降低地形',level:'设定地形高度'}[elevationMode]:'移除对象');draftRef.current=null;setDraft(null);}interaction.current=null;setSceneRequest(v=>v+1);};
 useEffect(()=>{const tile=hover&&active.map.tiles[hover.y*active.map.width+hover.x];onHover(hover&&tile?{x:hover.x,y:hover.y,elevation:tile.elevation}:null);},[active.map,hover,onHover]);
 const heights=useMemo(()=>active.map.tiles.reduce((r,t)=>({min:Math.min(r.min,t.elevation),max:Math.max(r.max,t.elevation)}),{min:16,max:0}),[active.map]);
 return <div className="viewport" ref={containerRef}>
  <canvas ref={canvasRef} tabIndex={0} aria-label="可编辑等距地图" data-testid="map-canvas" style={{width:size.w,height:size.h,cursor:space||tool==='pan'?'grab':tool==='select'?'default':'crosshair'}} onContextMenu={e=>e.preventDefault()} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={finish} onPointerCancel={()=>{interaction.current=null;draftRef.current=null;setDraft(null);setSceneRequest(v=>v+1);}} onPointerLeave={()=>{if(!interaction.current){setHover(null);onHover(null);}}}/>
  <div className="viewport-caption"><span className="live-dot"/>{nativeAssets&&(Object.keys(nativeAssets.sprites).length||Object.keys(nativeAssets.terrains).length)?<>混合素材预览 <span className="muted">/ 未映射项为示意 · 游戏未实测</span></>:<>地形示意预览 <span className="muted">/ 原创素材</span></>}</div>
  <div className="view-actions"><Button tip="显示网格 (G)" aria-pressed={grid} className={grid?'active':''} onClick={onGrid} icon={<Grid2X2 size={15}/>}/><Button tip="显示等高线 · 间隔 1 级" aria-pressed={contours} className={contours?'active':''} onClick={()=>setContours(v=>!v)} icon={<Mountain size={15}/>}/><Button tip="显示/隐藏对象" aria-pressed={showObjects} className={showObjects?'active':''} onClick={()=>setShowObjects(v=>!v)} icon={<Trees size={15}/>}/><i/><Button tip="适合窗口 (F)" onClick={fit} icon={<Maximize2 size={15}/>}/></div>
  <ElevationLegend minimum={heights.min} maximum={heights.max} current={hover?active.map.tiles[hover.y*active.map.width+hover.x]?.elevation:undefined} target={tool==='elevation'&&elevationMode==='level'?elevationTarget:undefined}/>
  <div className="map-compass"><span>N</span><svg viewBox="0 0 30 30" aria-hidden="true"><path d="M9 23 23 9M12 9H23V20" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg></div>
  <div className="minimap"><canvas ref={miniRef} title="点击定位地图" onClick={e=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*project.map.width,y=(e.clientY-r.top)/r.height*project.map.height,p=projectVertex(objectGround(field,{x,y} as MapObject));setCamera(c=>({...c,x:size.w/2-p.x*c.zoom,y:size.h/2-p.y*c.zoom}));}}/><span>{active.map.width} × {active.map.height}</span></div>
  <div className="zoom-controls"><Button tip="缩小" onClick={()=>zoom(.8)} icon={<Minus size={14}/>}/><span>{Math.round(camera.zoom*100)}%</span><Button tip="放大" onClick={()=>zoom(1.25)} icon={<Plus size={14}/>}/><Button tip="聚焦主要场景" onClick={frameScene} icon={<Crosshair size={14}/>}/></div>
  <div className="viewport-hint">{tool==='elevation'?(elevationMode==='level'?`拖动设为 ${elevationTarget} 级 · 一笔一次撤销`:'拖动雕刻 · 每格每笔 1 级 · 可撤销'):tool==='terrain'?'拖动绘制 · 一笔一次撤销':tool==='object'?'点击放置 · 选择后可拖动':tool==='erase'?'拖动移除未锁定对象':'点选对象 · 空格 + 拖动平移'}<span>滚轮缩放</span></div>
 </div>;
}
