import { useEffect, useRef, useState } from 'react';
import { FolderOpen, Image as ImageIcon, Layers3, RefreshCw, Trash2 } from 'lucide-react';
import { Button, Field, Modal } from './ui';
import type { Project, MapObject } from './types';
import { assetRequest, canAssignPreview, emptyNativeRender, limitationLabels, loadPreviewImage, spriteKey, type AssetEntry, type AssetPreview, type AssetStatus, type NativeRenderState, type UnitBinding } from './nativeAssets';
import './nativeAssets.css';
interface Props {open:boolean;onOpenChange:(v:boolean)=>void;project:Project;selected:MapObject|undefined;terrain:number;staticPreview:boolean;renderState:NativeRenderState;onRenderState:(state:NativeRenderState)=>void}
export default function NativeAssetsPanel({open,onOpenChange,project,selected,terrain,staticPreview,renderState,onRenderState}:Props){
 const [status,setStatus]=useState<AssetStatus|null>(null),[entries,setEntries]=useState<AssetEntry[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[query,setQuery]=useState(''),[kind,setKind]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState<AssetPreview|null>(null),[entry,setEntry]=useState<AssetEntry|null>(null),[civilization,setCivilization]=useState(1),[bindings,setBindings]=useState<UnitBinding[]>([]),[sourceTile,setSourceTile]=useState(96),[notice,setNotice]=useState('');
 const generation=useRef(0),active=useRef(true);useEffect(()=>{active.current=true;return()=>{active.current=false;generation.current++;};},[]);
 const desktop=typeof window!=='undefined'&&typeof (window as any).studio?.selectAssetDirectory==='function'&&!staticPreview;
 const currentBinding=bindings.find(b=>b.unitId===selected?.nativeId);
 const refresh=async()=>{const ticket=generation.current;const s=await assetRequest<AssetStatus>('status');if(ticket===generation.current&&active.current)setStatus(s);return s;};
 useEffect(()=>{if(open&&!staticPreview){void refresh().catch(()=>setError('本地素材服务未连接。目录选择需使用桌面应用。'));}},[open,staticPreview]);
 useEffect(()=>{if(!open||!status?.mounted||staticPreview){setEntries([]);return;}let current=true;const timer=setTimeout(()=>{void assetRequest<{entries:AssetEntry[];total:number}>(`catalog?query=${encodeURIComponent(query)}&kind=${encodeURIComponent(kind)}&offset=${offset}`).then(r=>{if(current){setEntries(r.entries);setTotal(r.total);}}).catch(e=>{if(current)setError(e.message);});},180);return()=>{current=false;clearTimeout(timer);};},[open,status?.revision,query,kind,offset,staticPreview]);
 const run=async(label:string,fn:()=>Promise<void>)=>{if(busy)return;setBusy(label);setError('');setNotice('');try{await fn();}catch(e){if(active.current)setError((e as Error).message);}finally{if(active.current)setBusy('');}};
 const choose=()=>run('只读扫描目录…',async()=>{const result=await (window as any).studio.selectAssetDirectory();if(result.error)throw new Error(result.error);if(result.cancelled)return;generation.current++;setStatus(result.status);setPreview(null);setEntry(null);setBindings([]);setQuery('');setKind('');setOffset(0);onRenderState(emptyNativeRender());});
 const decode=async(item:AssetEntry)=>{const ticket=++generation.current;const p=await assetRequest<AssetPreview>('decode',{assetId:item.id});if(ticket!==generation.current)return;setEntry(item);setPreview(p);await refresh();};
 const loadDat=()=>run('隔离进程解析 DAT…',async()=>{if(!entry)return;const s=await assetRequest<AssetStatus>('dat',{assetId:entry.id});setStatus(s);setBindings([]);setCivilization(s.dat?.civilizations.find(c=>c.id===1)?.id??s.dat?.civilizations[0]?.id??0);setNotice('DAT 已读取。请选择文明；此选择不修改原生场景玩家。');});
 const resolve=()=>run('解析本图单位引用…',async()=>{const ids=[...new Set(project.objects.map(o=>o.nativeId))];if(ids.length>256)throw new Error('本图超过 256 种单位，当前映射检查需要较小的场景。');const result=await assetRequest<{bindings:UnitBinding[]}>('bindings',{civilization,unitIds:ids});setBindings(result.bindings);setNotice(`已找到 ${result.bindings.filter(b=>b.resolved).length}/${ids.length} 种单位的独立 SLD。找到文件不等于已解码。`);});
 const mappedPreview=()=>run('解码 DAT 引用的精灵…',async()=>{if(!currentBinding?.assetId)return;const list=await assetRequest<{entries:AssetEntry[]}>('catalog?query='+encodeURIComponent(currentBinding.filename||'')+'&kind=sld');const item=list.entries.find(e=>e.id===currentBinding.assetId);if(!item)throw new Error('映射文件已失效，请重新扫描。');setSourceTile(Math.max(38,Math.min(512,currentBinding.tileWidth||96)));await decode(item);});
 const assign=()=>run('准备地图会话预览…',async()=>{if(!preview)return;if(!canAssignPreview(renderState,preview))throw new Error('会话预览已达到 1600 万像素或 16 个映射上限。请先清除地图预览。');const image=await loadPreviewImage(preview);if(preview.kind==='sld'){if(!selected)throw new Error('请先在地图选择一个对象。');onRenderState({...renderState,revision:preview.revision,sprites:{...renderState.sprites,[spriteKey(selected)]:{image,hotspot:preview.hotspot,scale:38/sourceTile,assetId:preview.assetId,label:entry?.name||'SLD'}}});setNotice(`已用于玩家 ${selected.player} 的单位 #${selected.nativeId}。仅会话外观，方向／玩家色／子图形未还原。`);}else{onRenderState({...renderState,revision:preview.revision,terrains:{...renderState.terrains,[terrain]:image}});setNotice(`已用于地形 #${terrain} 的实验平铺预览。此手动关联不代表 DAT 地形映射，未还原混合。`);}});
 const clear=()=>run('清除本机会话…',async()=>{setStatus(await assetRequest<AssetStatus>('clear',{}));generation.current++;setPreview(null);setEntry(null);setBindings([]);onRenderState(emptyNativeRender());});
 return <Modal open={open} onOpenChange={v=>{if(!v&&busy)return;onOpenChange(v);}} title="本地游戏素材 · 实验性静态预览" description="读取你选择的 AoE2 DE／许可模组目录。原始文件与解码缓存不上传、不加入工程导出。" wide>
  <div className="native-assets-intro"><div><strong>SLD 第 0 帧 · DDS 纹理 · DE DAT</strong><p>真实游戏素材尚未实测。阴影、玩家色、轮廓、损伤、方向、时代与复合建筑未完整还原。</p></div><span className="native-badge">本机只读</span></div>
  {!desktop&&<div className="callout">{staticPreview?'网页展示版不能读取游戏目录。请使用本地桌面应用。':'请从桌面应用打开此面板，再选择目录。浏览器不能直接提交主机路径。'} 没有游戏安装也可继续使用原创示意素材。</div>}
  <div className="native-controls"><Button disabled={!desktop||!!busy} icon={<FolderOpen size={15}/>} onClick={choose}>{status?.mounted?'重新选择目录':'选择游戏／模组资源目录'}</Button><Button disabled={!status?.mounted||!!busy} onClick={clear} icon={<Trash2 size={14}/>}>断开并清除缓存</Button><Button disabled={!!busy} onClick={()=>{onRenderState(emptyNativeRender());setNotice('地图已恢复原创示意素材。');}}>清除地图预览</Button></div>
  {status?.mounted&&<><div className="native-status"><span>发现 {status.total.toLocaleString()} 文件</span><span>SLD {status.counts.sld} / DDS {status.counts.dds} / DAT {status.counts.dat}</span><span>缓存 {(status.cacheBytes/1048576).toFixed(1)} MiB</span></div>{(status.truncated||status.skipped>0)&&<p className="callout">{status.truncated?'扫描达到目录大小／时间上限，请选择更小的资源子目录。 ':''}跳过 {status.skipped} 个链接、过大或不可读项目。</p>}
  <div className="native-browser"><section className="native-catalog"><div className="native-filter"><input aria-label="搜索本地素材" placeholder="按相对文件名搜索" value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/><select aria-label="素材格式" value={kind} onChange={e=>{setKind(e.target.value);setOffset(0);}}><option value="">全部</option>{['sld','dds','dat','smx','slp','drs'].map(k=><option key={k} value={k}>{k.toUpperCase()}</option>)}</select></div><div className="native-file-list">{entries.map(item=><button className={entry?.id===item.id?'selected':''} key={item.id} disabled={!!busy} onClick={()=>{setEntry(item);setPreview(null);if(item.previewable)void run('按需解码首帧…',()=>decode(item));}}><span>{item.kind==='dat'?<Layers3 size={14}/>:<ImageIcon size={14}/>}<strong>{item.name}</strong><small>{(item.bytes/1024).toFixed(0)} KiB</small></span><em>{item.relativePath}</em>{!item.previewable&&item.kind!=='dat'&&<small>仅索引，未实现解码</small>}</button>)}{!entries.length&&<p className="help-note">当前筛选没有可用文件。</p>}</div><div className="native-pages"><Button disabled={offset===0||!!busy} onClick={()=>setOffset(o=>Math.max(0,o-100))}>上一页</Button><span>{total?offset+1:0}–{Math.min(total,offset+100)} / {total}</span><Button disabled={offset+100>=total||!!busy} onClick={()=>setOffset(o=>o+100)}>下一页</Button></div></section>
  <section className="native-preview"><strong>{entry?.name||'选择文件以预览'}</strong>{preview?<><div className="native-image"><img src={preview.imageUrl} alt={`${entry?.name} 的解码预览`}/></div><div className="native-metadata">{preview.width} × {preview.height} px · 锚点 ({preview.hotspot.join(', ')}){preview.kind==='sld'?` · 帧 0/${preview.frameCount}`:''}<br/>SHA-256 {preview.sha256.slice(0,16)}…</div><p className="native-limitations">{preview.limitations.map(k=>limitationLabels[k]||k).join(' · ')}</p>{preview.kind==='sld'&&<Field label="预览源图每格宽度（像素，可校正）"><input type="number" min="38" max="512" value={sourceTile} onChange={e=>setSourceTile(Math.max(38,Math.min(512,Number(e.target.value)||96)))}/></Field>}<Button variant="primary" disabled={!!busy||(preview.kind==='sld'&&!selected)} onClick={assign}>{preview.kind==='sld'?`用于选中对象${selected?` #${selected.nativeId}`:''}的会话预览`:`手动用于地形 #${terrain} 的会话预览`}</Button>{preview.kind==='sld'&&!selected&&<small>先关闭面板，在地图选择一个对象。</small>}</>:entry?.kind==='dat'?<><p>隔离进程解析受支持的 DAT，读取文明、单位与站立图形引用。未知版本会拒绝。</p><Button disabled={!!busy} onClick={loadDat}>读取此 DAT</Button></>:<div className="native-empty"><ImageIcon size={38}/><p>按需读取 SLD 或 DDS<br/><small>没有下载或附带任何原游戏素材</small></p></div>}</section></div>
  {status.dat&&<div className="native-dat"><strong>DAT {status.dat.version} · 文明／单位映射</strong><div className="native-controls"><select aria-label="预览文明" value={civilization} onChange={e=>{setCivilization(+e.target.value);setBindings([]);}}>{status.dat.civilizations.map(c=><option key={c.id} value={c.id}>{c.id}: {c.name||'未命名文明'}</option>)}</select><Button disabled={!!busy} onClick={resolve} icon={<RefreshCw size={13}/>}>检查本图单位映射</Button></div><p>手动文明仅用于预览，不修改场景玩家或时代。当前选中：{selected?`玩家 ${selected.player} · 单位 #${selected.nativeId}`:'无对象'}。</p>{currentBinding&&<div className="callout">{currentBinding.resolved?<>图形 #{currentBinding.graphicId} → {currentBinding.filename}.sld · {currentBinding.angleCount} 方向 · {currentBinding.childGraphics} 子图形（暂不组合）<Button disabled={!!busy} onClick={mappedPreview}>预览此映射文件</Button></>:currentBinding.reason}</div>}{bindings.length>0&&<details><summary>解析结果：{bindings.filter(b=>b.resolved).length}/{bindings.length} 种单位找到文件</summary><ul>{bindings.slice(0,100).map(b=><li key={b.unitId}>#{b.unitId}: {b.resolved?b.filename:b.reason}</li>)}</ul></details>}</div>}
  </>}
  <p className="help-note">目录关系仅保留到退出应用。手动贴图关联与图片均不进入模型请求、自动保存、原生场景或 ZIP。SMX／SLP／DRS 目前只识别文件，不能显示。</p>
  {busy&&<div role="status" className="callout">{busy}</div>}{error&&<div role="alert" className="callout error">{error}</div>}{notice&&<div role="status" className="callout">{notice}</div>}<div className="dialog-actions"><Button disabled={!!busy} onClick={()=>onOpenChange(false)}>返回地图</Button></div>
 </Modal>;
}
